FROM ubuntu
USER root

# Update the package index and install necessary packages
RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    openssh-server \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common

# Add 'jenkins' user
RUN useradd -ms /bin/bash jenkins

# Install Docker Client
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    && apt-get update \
    && apt-get install -y docker-ce \
    && usermod -aG docker jenkins

# Generate SSH host keys
RUN ssh-keygen -t rsa -m pem -b 2048 -f /root/.ssh/id_rsa
RUN cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys

# Create the /run/sshd directory and set permissions
RUN mkdir -p /run/sshd && chmod 755 /run/sshd

# Install Kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/

# Start the SSH server and keep it running
CMD ["/bin/bash", "-c", "/usr/sbin/sshd -D"]